### ISSUE TITLE
比较basic的问题，requirements.txt安装失败。 

### ISSUE THREAD

**Issue by gohell9** [DataXujing/xiaoX#1]
Win的pycharm_64位安装失败。

ubt : pip install -r requirements.txt 同样失败呢，

**Comment by leiray** [comment]
requirements.txt这个文件面试一些依赖的包，分别手动执行下就可以了比如：  pip install tensorflow  ,pip install redis,pip install jieba  这些

**Comment by gohell9** [comment]
我知道啊，不过安装1.5.0版本的tf总是失败，换了中科大的pip源也失败。 所以想要一下pipenv的包 😂

**Comment by DataXujing** [comment]
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple tensorflow==1.5.0,试一下。

**Comment by gohell9** [comment]
(mytest-_wf8kayD) [root@m1 mytest]# python lx_bot_3.py train
Traceback (most recent call last):
  File "lx_bot_3.py", line 44, in <module>
    max_token_id = wordToken.load_file_list(['samples/question.txt', 'samples/answer.txt'], min_freq)
  File "/root/data/mytest/word_token.py", line 29, in load_file_list
    with open(file, 'r',encoding='utf-8') as file_object:
**FileNotFoundError: [Errno 2] No such file or directory: 'samples/question.txt'**


所以，我想问下，samples不会自己生成的？要去哪里下载吗？
  @@我尝试自己创建samples文件夹，还是报此错。
